rke2_token: ENC[AES256_GCM,data:/DpbBLs0wAQZoqRA5/HqfAFMXAr2H9NDuXjfV/wFHxiEQWvvG9T3qsq4HXX8H6dwsZLLwC9nKL6jBtBYredmbw==,iv:7D/I7+SrRtjjtd0QSHP2/S4L5sPOApqJ2P2I54q/2JE=,tag:ObbJpTtyd6C2VJe7EkpNBA==,type:str]
rke2_etcd_s3_access_key: ENC[AES256_GCM,data:hqpQy++2DwwgH2kRx4+F3f7+ySw=,iv:YNbVOT6OU5I2wsMu+1GjNUxRKuq70FQyiRvqPufxvc0=,tag:m1zBVadngu9AodSnOKeo/Q==,type:str]
rke2_etcd_s3_secret_key: ENC[AES256_GCM,data:/OWeGUGiJKn/HOP/6gF0a+xkFuOBI/DmlP4pXNuinbpZPkMQLz6Raw==,iv:fz2Kc2vhLQHp/VnC25tDpLrUgQFYUlTi5wRIiTE90oQ=,tag:Wd3z6mHf608yrXg7HGw+hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzZmMDZhT2hGb1RqaDRv
            TDJvTlRadGhGb0tiejQ3cnJ2cUZsclc4TjI4CmJPSDY2V29leFVqeDVGMkRDYjhl
            bUFqQ2s2Mzh5YTc5djBUeUoyM2gwQXMKLS0tIGVHMFlMZkM0ai9zazhEdE1DWlNa
            VFVHeFdrNFZXYkpRdThRRzB4elRiNzAKIku/kgH8q1y/owouH7XxXZVmfmBrzWaW
            19/nv/V9hUpu2FXCWVWz05FnsYmdeIXcNWp9HsT7mphVPIFW7hwY2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kr0vn2a7n42xpneeqfc7jsxngwmvr6gh7uyse80904kgldqzlersnwc5s4
    lastmodified: "2026-09-18T17:36:05Z"
    mac: ENC[AES256_GCM,data:c/oJcClblgfdEdyZsnx2JADYIPC5VI1LbzBIPnVNLy3+Ffq8GMmFYUPe+NEwIRJH6nYZMYJvIavhUS/BuVY9k06DcIJe7zEeYhlxS7dREa3psxl8iC43pITtKROrz0Qq0B42mbxfGZp/8/9j0EePsInUbIbWIwQ8ChIhqiRWr0w=,iv:4iF6f2x1b0pX0nD5gCxIWKuO5C7wU4QbCnznQnSSRU4=,tag:dv5D+YxHo2cTKWC+dv0z/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
