# The Ansible inventory is generated from the same nodes map that builds the
# VMs. Two hand-maintained copies of eight addresses drift; one does not.
resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.yml"
  file_permission = "0644"

  content = <<-YAML
    # GENERATED BY OPENTOFU - do not edit.
    # Source: tofu/nodes.auto.tfvars via tofu/ansible.tf
    ${yamlencode({
  all = {
    children = {
      rke2_servers = {
        hosts = { for k, v in var.nodes : k => { ansible_host = v.ip } if v.role == "server" }
      }
      rke2_agents = {
        hosts = { for k, v in var.nodes : k => { ansible_host = v.ip } if v.role == "agent" }
      }
      ops = {
        hosts = { for k, v in var.nodes : k => { ansible_host = v.ip } if v.role == "ops" }
      }
    }
    vars = {
      ansible_user                 = var.vm_user
      ansible_ssh_private_key_file = var.ssh_private_key_path
    }
  }
})}
  YAML
}
